import numpy as np
arr = np.array([[1,2],[3,4]])
arr1 = np.array([[1,2],[3,4]])
print("Addition of two arrays is :\n ",arr+arr1)
print("Subtraction of two arrays is :\n ",arr-arr1)
print("Multiplication of two arrays is :\n ",arr*arr1)
print("Multiplication of two arrays is :\n ",arr@arr1)
print("Multiplication of two arrays is :\n ",np.matmul(arr,arr1))
print("Mean of arr is :\n ",np.mean(arr))
print("Standard deviation of arr is :\n ",np.std(arr))
print("Variance of arr is :\n ",np.var(arr))
print("Minimum of arr is :\n ",np.min(arr))
print("Maximum of arr is :\n ",np.max(arr))
print("Argmin of arr is :\n ",np.argmin(arr))
print("Argmax of arr is :\n ",np.argmax(arr))
print("Square of arr is :\n ",np.square(arr))

print("Mean of arr1 is :\n ",np.mean(arr1))
print("Standard deviation of arr1 is :\n ",np.std(arr1))
print("Variance of arr1 is :\n ",np.var(arr1))
print("Minimum of arr1 is :\n ",np.min(arr1))
print("Maximum of arr1 is :\n ",np.max(arr1))
print("Argmin of arr1 is :\n ",np.argmin(arr1))
print("Argmax of arr1 is :\n ",np.argmax(arr1))
print("Square of arr1 is :\n ",np.square(arr1))
